### ISSUE TITLE
Templates do not work in some form fields

### ISSUE THREAD

**Issue by bozzmedia** [Briskine/briskine#524] opened 2024-02-26 22:23 UTC
#### Description
Some fields, especially those that are asking for email addresses tend to not work with a Briskine template.
I have one set as yourname@name.com set to "s" as the key, hit tab it does not autofill.
-

#### Steps to reproduce:
Firefox, Win10

While filling out forms notice that some email input fields do not accept Briskine template input. 

One source code I pulled from 
https://pro.portland.gov/_/

`<input type="email" name="Dl-o" id="Dl-o" class="DFI CTEF DocControlEmail FastEvtFieldKeyDown TAAuto TAAutoLeft FastEvtFieldFocus FieldEnabled FieldRequired" title="Required" value="" spellcheck="false" autocorrect="off" tabindex="0" style="" placeholder="Required" aria-required="true">`

I can add more as I come across them. I appreciate your efforts on this very useful addon. 
-

#### Related tickets/Sentry events:

-

**Comment by ghinda** [comment] 2024-02-27 08:32
Hi there,
I couldn't reproduce the exact issue you mentioned. I've tested the main username field on https://pro.portland.gov/_/.
![Peek 2024-02-27 10-27](https://github.com/Briskine/briskine/assets/325171/fa4ff1b1-6b36-4dfd-94fc-a35b9da21774)

I couldn't find an email field there. Maybe it's behind the login? Can you show me some other websites where this is happening? 

Can you also test it out on Chrome? Just trying to see if it's Firefox-specific.

**Comment by bozzmedia** [comment] 2024-02-27 20:26
The updated URL I posted should be: 
https://pro.portland.gov/_/

Test it on the Email field at the bottom of the form.

I don't have briskine installed for Chrome but I can do that.

![image](https://github.com/Briskine/briskine/assets/4435114/d851b2e3-85d7-4d78-8c19-ab32b262c697)

**Comment by ghinda** [comment] 2024-02-28 10:22
Thank you for the screenshot. The issue is now fixed in the latest version `7.11.3`.
You can force Firefox to update to the latest version in *Manage Extensions > Cog button > Check for updates*.

**Closed by ghinda** 2024-02-28 10:22 UTC
Labels: bug

**Comment by bozzmedia** [comment] 2024-02-28 23:59
Wow that was fast, thanks so much for the quick work :)
